# Generated by Django 4.2.23 on 2025-09-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name or identifier for this sample.', max_length=255, verbose_name='Sample Name')),
                ('lot_number', models.CharField(blank=True, help_text='The production lot number, if applicable.', max_length=100, verbose_name='Lot Number')),
                ('description', models.TextField(blank=True, help_text='Any additional notes or description for this sample.', verbose_name='Description')),
                ('source_location', models.ForeignKey(blank=True, help_text='The location where this sample is stored, if not in a specific space.', null=True, on_delete=django.db.models.deletion.PROTECT, to='location_configuration.location', verbose_name='Source Location')),
            ],
            options={
                'verbose_name': 'Sample Item',
                'verbose_name_plural': 'Sample Items',
                'ordering': ['name'],
            },
        ),
    ]
