# Generated by Django 4.2.23 on 2025-09-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleitem',
            name='catalog_number',
            field=models.CharField(blank=True, help_text='The catalog number for the sample, if applicable.', max_length=100, verbose_name='Catalog Number'),
        ),
    ]
