# Generated by Django 4.2.23 on 2025-09-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name for this specific location instance.', max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name for this type of location.', max_length=255, unique=True, verbose_name='Name')),
                ('can_store_samples', models.BooleanField(default=False, help_text='Indicates if locations of this type can directly store samples.', verbose_name='Can Store Samples')),
                ('can_have_spaces', models.BooleanField(default=False, help_text='If true, instances of this type are grid containers (e.g., a rack or plate).', verbose_name='Can Have Spaces')),
                ('space_rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Grid Rows')),
                ('space_cols', models.PositiveIntegerField(blank=True, null=True, verbose_name='Grid Columns')),
                ('allowed_parent_types', models.ManyToManyField(blank=True, help_text='Defines which location types this type can be nested within.', to='location_configuration.locationtype', verbose_name='Allowed Parent Types')),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('occupied_by_location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_space', to='location_configuration.location')),
            ],
            options={
                'verbose_name': 'Location Space',
                'verbose_name_plural': 'Location Spaces',
                'ordering': ['parent_location', 'row', 'col'],
            },
        ),
    ]
