# Generated by Django 4.2.23 on 2025-09-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample_control', '0001_initial'),
        ('location_configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationspace',
            name='occupied_by_sample_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_space', to='sample_control.sampleitem'),
        ),
        migrations.AddField(
            model_name='locationspace',
            name='parent_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='location_configuration.location', verbose_name='Parent Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent location this location is directly nested inside.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_locations', to='location_configuration.location', verbose_name='Parent Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='source_location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location_configuration.locationtype', verbose_name='Location Type'),
        ),
        migrations.AddConstraint(
            model_name='locationspace',
            constraint=models.CheckConstraint(check=models.Q(('occupied_by_location__isnull', False), ('occupied_by_sample_item__isnull', False), _negated=True), name='only_one_occupant'),
        ),
        migrations.AlterUniqueTogether(
            name='locationspace',
            unique_together={('parent_location', 'row', 'col')},
        ),
    ]
